### PR TITLE
Migrates to dart:ui_web APIs.

### PR DESCRIPTION
**Pull request by malibayram**
Update dart_ui_fix and web.dart files

### CODE REVIEW

**Review by umutckmk2 — APPROVED** [review]
Suitable for merging.

**Review by oneraytas — APPROVED** [review]

**Comment by Mahad61** [comment]
> @Mahad61 thanks for your fast response. Can you mention the issues to make things faster?

in the web.dart file you have made some changes and i think due to that reason when you try to open url in iframe then its not working.
When you run the example try to click on  flutter.dev or ycombinator.com buttons

**Comment by malibayram** [comment]
Since the 'contenWindow' of the 'iframe' is no longer working, I had to set the content by changing the 'iframe.src'. I refactored some code to refresh the page with the new content, which appears to be working now. Could you please review it again?

**Comment by malibayram** [comment]
Thank you for approving my PR. If you could authorize me on [pub.dev](https://pub.dev/), I can update the package version there as well. This is necessary as it is not compatible with the latest Flutter version on the web. @Mahad61

**Comment by jiajiawei** [comment]
Thanks for "Migrates to dart:ui_web APIs." but I find some bugs: for `iframe.src` instead of `iframe.contentWindow.location.href`.

1. Click button "Change content to URL that allows iFrames embedding(https://flutter.dev/)"
2. Click button "Call platform independent Js method (console.log)"

Before: It will throw an exception and `showAlertDialog`.
After: nothing.

In my case, I use `postMessage` many times until iframe content load completed, and the iframe will send back `postMessage`. But it's available now.
So... I need the old window / iframe.

**Pull request merged**
